### ISSUE TITLE
Setup Tailwind and Daisy UI

### ISSUE THREAD

**Issue by andradajus** [seenjey07/NimbusAirways#1]
https://tailwindcss.com/docs/guides/create-react-app
https://daisyui.com/docs/install/
Palagay na rin ako nito sa configs. via tailwind.config.js after mo install yung tailwind sa frontend 

```
export default {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  daisyui: {
    styled: true, 
    utils: true,
    themes: [
      {
        mytheme: {
        "primary": "#00b7ff",
        "secondary": "#00e700",
        "accent": "#008cff",
        "neutral": "#0a0f03",
        "base-100": "#281e25",
        "info": "#00ffff",
        "success": "#82f600",
        "warning": "#e67200",
        "error": "#ff0048",
        },
      },
    ],
  },
    extend: {},
    // eslint-disable-next-line no-undef
    plugins: [require("@tailwindcss/typography"), require("daisyui")],
}

```
bale config. palitan mo nalnag yung themes kung ano yung specific kung by themes. and yan yung format kung custom via theme generator 😄

**Comment by seenjey07** [comment]
Ang cute netong project feature hahaha.
Btw, luxury for a dark theme sana and autumn for a light theme.
