### ISSUE TITLE
Booking API (CRUD)

### ISSUE THREAD

**Issue by andradajus** [seenjey07/NimbusAirways#14]
POST /api/bookings: Create a new flight reservation.

GET /api/bookings/{bookingId}: Get details of a specific booking.

PUT /api/bookings/{bookingId}: Update a booking (e.g., add passengers, change seats).

DELETE /api/bookings/{bookingId}: Cancel a booking.

**Comment by seenjey07** [comment]
Pwede na muna for now hahaha
